// Curated automation library for the AI lead-magnet.
// Every item is buildable with Claude Code plus common APIs, and either
// touches revenue directly or saves the owner at least 2 hours a week.

export type MoneyMech = "makes_money" | "saves_time" | "both";
export type BuildTime = "60min" | "half_day" | "week";

export interface LibItem {
  id: string; // kebab-case unique
  name: string; // plain-english, punchy, sentence case
  what: string; // 1-2 sentences, what it does, written to the owner ("you")
  mech: MoneyMech;
  mathHint: string; // formula the AI computes with the owner's numbers
  time: BuildTime;
  tools: string; // favor tools they already have
  surprise?: boolean; // true = "most people don't know this is automatable"
  planSeed: string; // 3-5 terse build steps separated by " | "
}

export interface CategoryLib {
  key: string;
  label: string;
  items: LibItem[];
}

export const LIBRARY: CategoryLib[] = [
  {
    key: "online",
    label: "Online services: agencies, coaches, consultants",
    items: [
      {
        id: "speed-to-lead-responder",
        name: "Speed-to-lead instant responder",
        what: "The second a lead fills your form or DMs you, they get a personal-sounding reply and a booking link within 60 seconds, day or night. Leads answered in under 5 minutes convert several times better than leads answered in an hour.",
        mech: "makes_money",
        mathHint: "leads_per_week * slow_response_pct * close_rate_lift * avg_client_value = monthly recovered revenue (lift of 0.1 to 0.2 on leads currently answered after 30 min)",
        time: "60min",
        tools: "Claude Code + your existing GHL or HubSpot, nothing new to buy",
        planSeed: "Webhook on new lead in CRM | Claude drafts a reply using the lead's own form answers | send via CRM SMS or email with booking link | tag lead as contacted | log response time to a sheet",
      },
      {
        id: "no-show-rescue",
        name: "No-show rescue sequence",
        what: "When someone misses a sales call, you get a rebooking sequence that references what they originally said they wanted, sent automatically at the right intervals. Most no-shows are never chased properly, so this is found money.",
        mech: "makes_money",
        mathHint: "no_shows_per_week * rebook_rate * show_rate * close_rate * avg_client_value * 4 = monthly recovered revenue (rebook_rate around 0.3 with a good sequence)",
        time: "60min",
        tools: "Claude Code + your calendar tool + GHL or email, nothing new to buy",
        planSeed: "Detect missed appointment via calendar or CRM status | pull the lead's original form answers | Claude writes a personal rebook message | send at 10 min, 1 day, 3 days | stop on rebook",
      },
      {
        id: "dead-lead-reactivation",
        name: "Dead-lead reactivation machine",
        what: "Every lead who ghosted in the last 6-12 months gets a short, human 9-word style check-in written from their original context. You are sitting on a list that already cost you money to build.",
        mech: "makes_money",
        mathHint: "dead_leads_count * reply_rate * close_rate * avg_client_value = one-time recovered revenue, then dead_leads_per_month * same rates = ongoing (reply_rate 0.05 to 0.15)",
        time: "60min",
        tools: "Claude Code + your existing CRM export or a spreadsheet",
        planSeed: "Export ghosted leads with last-contact date | Claude writes one-line check-ins per lead from their notes | send in daily batches to stay deliverable | route replies to your phone | track revives in a sheet",
      },
      {
        id: "proposal-from-call-notes",
        name: "Proposal generator from call notes",
        what: "Paste or auto-pull your sales call transcript and a full custom proposal comes back in your voice, with their goals, scope, and pricing filled in. Same-day proposals close more, and you get your evenings back.",
        mech: "both",
        mathHint: "(proposals_per_week * hours_per_proposal * owner_hourly_value * 4) + (proposals_per_week * 4 * close_rate_lift * avg_client_value) = monthly value (same-day delivery lifts close rate roughly 0.05 to 0.1)",
        time: "half_day",
        tools: "Claude Code + your call recorder (Zoom, Fathom, or phone notes) + Google Docs",
        surprise: true,
        planSeed: "Ingest transcript from recorder API or paste | Claude extracts goals, objections, budget signals | fill your proposal template with scope and pricing rules | output Google Doc or PDF | send draft to you for one-tap approval",
      },
      {
        id: "testimonial-miner",
        name: "Testimonial miner from call transcripts",
        what: "Every client call gets scanned for win statements and before-after moments, which are turned into ready-to-post testimonials and case study snippets. You already have proof on tape, you are just not harvesting it.",
        mech: "makes_money",
        mathHint: "calls_per_week * 4 * proof_snippets_per_call = monthly proof assets; value = current_close_rate * proof_lift * leads_per_month * avg_client_value (proof_lift 0.05 to 0.1 on close rate)",
        time: "half_day",
        tools: "Claude Code + your existing call recordings, nothing new to buy",
        surprise: true,
        planSeed: "Pull transcripts from recorder API | Claude flags quantified wins and emotional before-after lines | format as testimonial cards and case study bullets | drop into a shared doc | weekly digest of the best 5",
      },
      {
        id: "churn-risk-tone-detector",
        name: "Client churn-risk detector",
        what: "Reads the tone and cadence of client messages, check-in attendance, and result trends, then warns you which clients are drifting before they quit. Saving one client usually pays for a year of this.",
        mech: "makes_money",
        mathHint: "clients_count * monthly_churn_rate * save_rate * avg_client_value * months_retained = monthly protected revenue (save_rate around 0.3 when you intervene early)",
        time: "week",
        tools: "Claude Code + your Slack or client chat + your CRM",
        surprise: true,
        planSeed: "Pull recent client messages and session attendance | Claude scores sentiment shift, response lag, and cancellation language | rank clients by risk weekly | alert you with a suggested save move per client | log outcomes to tune scoring",
      },
      {
        id: "client-report-writer",
        name: "Weekly client report writer",
        what: "Client-facing progress reports write themselves from your project tracker, ad accounts, or coaching notes, in your voice, ready to send. Reporting is hours of unpaid admin every single week.",
        mech: "saves_time",
        mathHint: "clients_count * minutes_per_report / 60 * owner_hourly_value * 4 = monthly time value reclaimed",
        time: "half_day",
        tools: "Claude Code + Google Sheets + wherever your delivery data lives",
        planSeed: "Connect data sources per client | Claude drafts the report against your template and voice sample | flag anomalies worth a personal note | queue drafts for one-click approval | auto-send on your reporting day",
      },
      {
        id: "content-repurposer",
        name: "Content repurposing engine",
        what: "One long video or call becomes a week of posts: clips scripts, an email, and platform-native captions in your voice. You create once and it multiplies without you.",
        mech: "saves_time",
        mathHint: "hours_on_content_per_week * repurpose_share * owner_hourly_value * 4 = monthly time value (repurpose_share is the fraction of content hours spent reformatting, usually 0.5+)",
        time: "half_day",
        tools: "Claude Code + your existing recordings + a scheduler you already use",
        planSeed: "Transcribe source video or call | Claude extracts hooks and standalone segments | rewrite per platform with your voice rules | output to a review sheet | push approved posts to scheduler",
      },
      {
        id: "invoice-chaser",
        name: "Polite invoice chaser",
        what: "Overdue invoices get followed up automatically with escalating but friendly messages, and you get pinged only when someone is seriously late. Chasing money is the worst job in the business, so stop doing it by hand.",
        mech: "makes_money",
        mathHint: "overdue_amount_avg * collection_lift + (hours_chasing_per_week * owner_hourly_value * 4) = monthly value (collection_lift 0.2 to 0.4 of chronically late amounts)",
        time: "60min",
        tools: "Claude Code + Stripe or your invoicing tool + email",
        planSeed: "Poll invoices past due daily | Claude writes tone-matched reminders that escalate at 3, 7, 14 days | send from your address | pause on payment or reply | weekly aging summary to you",
      },
      {
        id: "onboarding-autopilot",
        name: "Client onboarding autopilot",
        what: "New client signs, and everything fires without you: welcome email, intake form, folder setup, kickoff scheduling, and internal checklist. First impressions get better while you do zero admin.",
        mech: "both",
        mathHint: "(new_clients_per_month * onboarding_hours * owner_hourly_value) + (new_clients_per_month * early_churn_rate * save_share * avg_client_value) = monthly value (clean onboarding cuts early churn meaningfully)",
        time: "week",
        tools: "Claude Code + Google Workspace + your CRM, nothing new to buy",
        planSeed: "Trigger on deal-won in CRM | create Drive folder and docs from templates | send personalized welcome and intake | book kickoff via calendar link | notify you with a one-page client brief",
      },
      {
        id: "lead-qualifier-scorer",
        name: "Lead scoring on autopilot",
        what: "Every inbound lead gets scored against your best-client profile using their form answers and any public info, so your calendar fills with buyers, not browsers. You stop spending call slots on people who were never going to pay.",
        mech: "makes_money",
        mathHint: "calls_per_week * unqualified_pct * hours_per_call * owner_hourly_value * 4 + (freed_slots * close_rate * avg_client_value) = monthly value",
        time: "60min",
        tools: "Claude Code + your form tool + your CRM",
        planSeed: "Webhook on form submit | Claude scores answers against your ideal-client rubric | route A-leads to priority calendar, C-leads to nurture | write a pre-call brief per booked lead | log scores vs outcomes",
      },
      {
        id: "call-recap-next-steps",
        name: "Call recap and next-steps email",
        what: "Every sales or client call ends with a clean recap email already drafted: what was agreed, next steps, and dates. Follow-through is where deals and renewals quietly die.",
        mech: "saves_time",
        mathHint: "calls_per_week * recap_minutes / 60 * owner_hourly_value * 4 = monthly time value reclaimed",
        time: "60min",
        tools: "Claude Code + your call recorder + email",
        planSeed: "Pull transcript after each call | Claude drafts recap with commitments and owners | you approve or edit in one tap | send and log to CRM | create follow-up reminders automatically",
      },
      {
        id: "referral-ask-trigger",
        name: "Referral ask at the moment of a win",
        what: "When a client hits a milestone or sends praise, a personal referral ask goes out while they are happiest. Referrals are your cheapest leads and almost nobody asks at the right moment.",
        mech: "makes_money",
        mathHint: "client_wins_per_month * ask_rate * referral_rate * close_rate * avg_client_value = monthly referral revenue (referral_rate 0.1 to 0.2 when asked at a win)",
        time: "60min",
        tools: "Claude Code + your client chat or email, nothing new to buy",
        planSeed: "Detect win signals from messages or milestone data | Claude drafts a personal ask referencing the win | you approve, it sends | track referrals by source | thank-you follow-up on intro",
      },
    ],
  },
  {
    key: "local",
    label: "Local and brick-and-mortar service businesses: trades, clinics, salons, restaurants",
    items: [
      {
        id: "missed-call-text-back",
        name: "Missed-call text-back",
        what: "Every call you miss gets an instant text: sorry we missed you, here is a booking link or a promise to call back in 10 minutes. Missed calls are the biggest silent leak in local business.",
        mech: "makes_money",
        mathHint: "missed_calls_per_week * booking_rate * close_rate * avg_job_value * 4 = monthly recovered revenue (booking_rate 0.2 to 0.4 with an instant text)",
        time: "60min",
        tools: "Claude Code + your existing phone number via GHL or Twilio",
        planSeed: "Detect missed call event | fire instant SMS with booking link | Claude handles the reply conversation and books | alert you for urgent jobs | log every recovered call to a sheet",
      },
      {
        id: "review-request-engine",
        name: "Review request engine",
        what: "Every finished job or visit triggers a personal review request at the right moment, with a direct Google link. More reviews means you win the map pack, which means free leads forever.",
        mech: "makes_money",
        mathHint: "jobs_per_week * review_rate * 4 = new reviews per month; value = map_rank_lead_lift * leads_per_month * close_rate * avg_job_value (review_rate around 0.2 with timed asks)",
        time: "60min",
        tools: "Claude Code + your booking system or job sheet + SMS",
        planSeed: "Trigger on job-complete status | wait for the happy moment, then SMS a personal ask | include direct review link | skip unhappy customers, route them to you instead | weekly review count report",
      },
      {
        id: "review-response-writer",
        name: "Review responses in your voice",
        what: "Every Google review, good or bad, gets a draft reply that sounds like you, ready to approve from your phone. Owners who respond to everything look alive and rank better, but nobody has the time.",
        mech: "saves_time",
        mathHint: "reviews_per_month * minutes_per_response / 60 * owner_hourly_value = monthly time value, plus consistent responses feed the map-rank lift",
        time: "60min",
        tools: "Claude Code + your Google Business Profile, nothing new to buy",
        surprise: true,
        planSeed: "Poll new reviews via Google Business API | Claude drafts reply matching your tone samples | flag negative reviews with a de-escalation draft | one-tap approve from phone | post and log",
      },
      {
        id: "quote-follow-up",
        name: "Quote follow-up that never forgets",
        what: "Every quote you send gets followed up at day 2, 5, and 10 with short human messages until they answer. Most trades lose jobs not on price but because the other guy followed up.",
        mech: "makes_money",
        mathHint: "quotes_per_week * unanswered_pct * follow_up_close_rate * avg_job_value * 4 = monthly recovered revenue (follow_up_close_rate 0.1 to 0.2 of silent quotes)",
        time: "60min",
        tools: "Claude Code + your quote tool or spreadsheet + SMS or email",
        planSeed: "Log every sent quote with amount and date | schedule follow-ups until reply or decline | Claude writes each touch referencing the job | route replies to your phone | weekly open-quote pipeline summary",
      },
      {
        id: "supplier-price-watcher",
        name: "Supplier price-list watcher",
        what: "Watches the supplier price lists and emails you actually use, and when materials go up it flags every quote template and standard job price that is now underpriced. Silent supplier increases quietly eat your margin all year.",
        mech: "both",
        mathHint: "jobs_per_month * material_cost_share * avg_supplier_increase_pct * avg_job_value = monthly margin protected when prices update instead of lag",
        time: "half_day",
        tools: "Claude Code + supplier PDFs or emails + your price spreadsheet",
        surprise: true,
        planSeed: "Ingest supplier price PDFs or emails on arrival | Claude diffs against last known prices | map changed items to your quote templates | alert you with suggested new prices | one-tap update to the pricing sheet",
      },
      {
        id: "permit-status-checker",
        name: "Permit and inspection status checker",
        what: "Checks your council or city portal for permit and inspection status on every open job and tells you the moment something moves or stalls. No more refreshing portals or jobs sitting idle because paperwork cleared and nobody noticed.",
        mech: "saves_time",
        mathHint: "open_permits_count * checks_per_week * minutes_per_check / 60 * owner_hourly_value * 4 + (idle_days_saved * crew_day_value) = monthly value",
        time: "half_day",
        tools: "Claude Code + the permit portal you already log into",
        surprise: true,
        planSeed: "Script portal login and status scrape per job number | run on a daily schedule | diff against yesterday's status | SMS you on any change | flag jobs stalled past your threshold",
      },
      {
        id: "appointment-reminder-reschedule",
        name: "Reminders that fill their own gaps",
        what: "Customers get reminded before appointments, and if they need to move, the system reschedules them by text without a phone call. Fewer no-shows, zero phone tag.",
        mech: "makes_money",
        mathHint: "appointments_per_week * no_show_rate * reduction_share * avg_ticket_value * 4 = monthly recovered revenue (good reminders cut no-shows by around half)",
        time: "60min",
        tools: "Claude Code + your booking calendar + SMS",
        planSeed: "Send reminder at 24h and 2h | Claude handles reschedule replies against live availability | update calendar automatically | confirm new slot to customer | log no-show rate weekly",
      },
      {
        id: "instant-quote-builder",
        name: "Instant quote from photos and a description",
        what: "Customer sends photos and a description, and a priced quote draft lands in your inbox for approval, built from your own pricing rules. Quoting same-day instead of next-week wins jobs on speed alone.",
        mech: "makes_money",
        mathHint: "quotes_per_week * 4 * speed_close_lift * avg_job_value + (quotes_per_week * quote_hours * owner_hourly_value * 4) = monthly value (cutting quote_turnaround_days from 3+ to same day lifts close rate 0.1+)",
        time: "week",
        tools: "Claude Code + your phone camera + a pricing spreadsheet you already have",
        planSeed: "Intake form or SMS collects photos and job details | Claude estimates scope from images and description | apply your rate card and materials pricing | generate branded quote PDF for your approval | send and enter the follow-up sequence",
      },
      {
        id: "dead-quote-reactivation",
        name: "Old quote reactivation blitz",
        what: "Everyone you quoted in the past year who never booked gets a short check-in, with a reason to act now. These people already raised their hand and priced the job.",
        mech: "makes_money",
        mathHint: "old_quotes_count * reply_rate * close_rate * avg_job_value = one-time recovered revenue (reply_rate 0.05 to 0.15 on a personal check-in)",
        time: "60min",
        tools: "Claude Code + your quote history, even if it is a shoebox spreadsheet",
        planSeed: "Export past quotes with job and date | Claude writes one-line check-ins referencing each job | send in daily batches | route replies to your phone | track booked jobs by batch",
      },
      {
        id: "schedule-gap-filler",
        name: "Cancellation gap filler",
        what: "When someone cancels, your waitlist gets texted in order until the slot is filled, automatically. Empty chairs and empty crew hours are pure lost revenue you can claw back.",
        mech: "makes_money",
        mathHint: "cancellations_per_week * fill_rate * avg_ticket_value * 4 = monthly recovered revenue (fill_rate 0.4 to 0.7 with an instant waitlist text)",
        time: "half_day",
        tools: "Claude Code + your booking calendar + SMS",
        planSeed: "Detect cancellation event | pull waitlist and nearby upcoming bookings | text offers one at a time with a claim window | book the first yes and update calendar | notify you when filled",
      },
      {
        id: "job-costing-report",
        name: "Weekly job margin report",
        what: "Every week you get a plain-english report: which jobs made money, which lost, and why, from your invoices and materials costs. Most owners find one chronically underpriced service in the first month.",
        mech: "saves_time",
        mathHint: "hours_on_bookkeeping_per_week * owner_hourly_value * 4 + (underpriced_jobs_per_month * margin_fix_value) = monthly value",
        time: "half_day",
        tools: "Claude Code + your invoicing tool + supplier receipts",
        planSeed: "Pull invoices and cost data weekly | match costs to jobs | Claude computes margin per job and flags outliers | write a 10-line owner summary | SMS or email it every Friday",
      },
      {
        id: "after-hours-ai-receptionist",
        name: "After-hours AI receptionist",
        what: "Evenings and weekends, an AI answers your line or texts back instantly, answers common questions, and books jobs into your calendar. You capture the customers who call the next name on the list when you do not pick up.",
        mech: "makes_money",
        mathHint: "after_hours_calls_per_week * booking_rate * close_rate * avg_job_value * 4 = monthly captured revenue (booking_rate 0.3+ when answered instantly vs voicemail)",
        time: "week",
        tools: "Claude Code + Twilio or your GHL number + your booking calendar",
        planSeed: "Route after-hours calls to voice or SMS agent | Claude answers FAQs from your services and pricing doc | qualify and book into open slots | escalate emergencies to your mobile | morning digest of every conversation",
      },
      {
        id: "rebooking-reminder",
        name: "Comeback reminders for repeat services",
        what: "Customers due for their next service, a 6-week trim, annual HVAC check, dental recall, get a personal nudge with a booking link at exactly the right time. Repeat revenue you currently leave to customer memory.",
        mech: "makes_money",
        mathHint: "customers_due_per_month * rebook_rate * avg_ticket_value = monthly recurring revenue added (rebook_rate 0.2 to 0.4 on timed personal nudges)",
        time: "60min",
        tools: "Claude Code + your customer list + SMS, nothing new to buy",
        planSeed: "Compute next-due date per customer from service history | schedule nudges at due date minus a week | Claude personalizes each message | booking link straight into calendar | track rebook rate monthly",
      },
    ],
  },
  {
    key: "ecom",
    label: "E-commerce and physical products",
    items: [
      {
        id: "cart-rescue-plus",
        name: "Abandoned cart rescue that actually sells",
        what: "Beyond the default reminder email, abandoners get messages written around the exact products they left, with objections answered from your reviews. The default flow recovers crumbs, this recovers meals.",
        mech: "makes_money",
        mathHint: "sessions_per_month * cart_abandon_rate * extra_recovery_lift * avg_order_value = monthly recovered revenue (extra_recovery_lift 0.03 to 0.08 over the stock flow)",
        time: "60min",
        tools: "Claude Code + Shopify + the email tool you already use",
        planSeed: "Pull abandoned checkouts via Shopify API | Claude writes product-specific rescue copy using review themes | send a 3-touch sequence | hold discounts for second touch only | report recovered revenue weekly",
      },
      {
        id: "review-mining-copy",
        name: "Review mining for product copy",
        what: "Reads every review of your products and your competitors' and rewrites your product pages using the exact words buyers use, including the objections they mention. Customers write better copy than copywriters, you just have to mine it.",
        mech: "makes_money",
        mathHint: "monthly_sessions * conversion_rate * conversion_lift_share * avg_order_value = monthly added revenue (voice-of-customer copy lifts conversion 0.05 to 0.15 relative)",
        time: "half_day",
        tools: "Claude Code + your Shopify reviews, nothing new to buy",
        surprise: true,
        planSeed: "Pull reviews per product | Claude clusters praised benefits, objections, and exact phrases | rewrite title, bullets, and description per product | output side-by-side for approval | push updates via Shopify API",
      },
      {
        id: "chargeback-evidence-assembler",
        name: "Chargeback evidence assembler",
        what: "When a dispute hits, the full evidence pack, order record, delivery confirmation, customer emails, policy screenshots, assembles itself and files before the deadline. Most merchants lose winnable disputes because compiling evidence is miserable.",
        mech: "makes_money",
        mathHint: "chargebacks_per_month * win_rate_lift * avg_order_value + (chargebacks_per_month * hours_per_dispute * owner_hourly_value) = monthly value (proper evidence roughly doubles win rate)",
        time: "half_day",
        tools: "Claude Code + Stripe or Shopify Payments + your email and shipping tools",
        surprise: true,
        planSeed: "Webhook on new dispute | gather order, tracking, delivery scan, and customer correspondence | Claude writes the rebuttal letter to network rules | compile PDF pack | submit via API before deadline and log outcome",
      },
      {
        id: "restock-predictor",
        name: "Restock predictor from sales velocity",
        what: "Watches sell-through speed per SKU against supplier lead times and tells you what to reorder and when, before you stock out. Stockouts on winners are the most expensive mistake in ecom.",
        mech: "both",
        mathHint: "stockout_days_per_month * avg_daily_revenue_of_affected_skus = monthly revenue protected, plus hours_on_inventory_per_week * owner_hourly_value * 4",
        time: "half_day",
        tools: "Claude Code + Shopify inventory data, nothing new to buy",
        surprise: true,
        planSeed: "Pull sales velocity and stock levels per SKU daily | project days-until-stockout vs supplier lead time | Claude drafts the reorder list with quantities | flag slowing SKUs to avoid over-ordering | weekly buy-sheet to your inbox",
      },
      {
        id: "post-purchase-upsell",
        name: "Post-purchase upsell flow",
        what: "Right after checkout and again at delivery, buyers get one smart, relevant offer based on what they just bought. The cheapest customer to sell is the one who just bought.",
        mech: "makes_money",
        mathHint: "orders_per_month * upsell_take_rate * upsell_avg_value = monthly added revenue (take_rate 0.05 to 0.15 on relevant one-click offers)",
        time: "60min",
        tools: "Claude Code + Shopify + your email tool",
        planSeed: "Map complement products per top SKU | trigger offer email at purchase and at delivery scan | Claude writes the pitch per product pair | one-click add via discount link | track attach rate per pair",
      },
      {
        id: "support-inbox-drafts",
        name: "Support inbox auto-drafts",
        what: "Every support email arrives with a suggested reply already written from your policies and the customer's order history, so you approve instead of compose. Cuts support time by more than half without losing your voice.",
        mech: "saves_time",
        mathHint: "ticket_count_per_week * minutes_per_ticket * draft_time_saved_share / 60 * owner_hourly_value * 4 = monthly time value (draft_time_saved_share around 0.6)",
        time: "half_day",
        tools: "Claude Code + your inbox + Shopify order data",
        planSeed: "Ingest incoming support email | pull the customer's order and tracking | Claude drafts reply per your policy doc and tone | queue for one-tap approve or edit | auto-handle pure tracking questions end to end",
      },
      {
        id: "wismo-auto-answer",
        name: "Where-is-my-order auto answer",
        what: "Tracking questions, usually a third of your inbox, get answered instantly and accurately with live carrier status, without you touching them. This is the most automatable ticket type in existence.",
        mech: "saves_time",
        mathHint: "ticket_count_per_week * wismo_share * minutes_per_ticket / 60 * owner_hourly_value * 4 = monthly time value (wismo_share commonly 0.3 to 0.4)",
        time: "60min",
        tools: "Claude Code + your inbox + carrier tracking APIs",
        planSeed: "Classify incoming email as WISMO | look up order and live tracking | Claude writes a status reply with honest ETA | send automatically, escalate stuck shipments to you | log deflection rate",
      },
      {
        id: "delivery-timed-review-request",
        name: "Review requests timed to delivery",
        what: "Review asks go out a set number of days after the package actually arrives, not after checkout, personalized to the product. Timing alone can double your review rate, and reviews compound conversion.",
        mech: "makes_money",
        mathHint: "orders_per_month * review_rate_lift = extra reviews per month; value = monthly_sessions * conversion_rate * social_proof_lift * avg_order_value",
        time: "60min",
        tools: "Claude Code + Shopify + carrier tracking + your email tool",
        planSeed: "Watch tracking for delivered scans | wait product-appropriate days | Claude writes the ask per product | route 1-2 star intents to support instead of public review | track review rate by product",
      },
      {
        id: "lapsed-customer-winback",
        name: "Lapsed customer winback",
        what: "Customers who have not bought in 60-90 days get a personal-feeling nudge built from what they bought before. Winning back a past customer is 5x cheaper than buying a new one.",
        mech: "makes_money",
        mathHint: "lapsed_customers_count * winback_rate * avg_order_value = recovered revenue per campaign (winback_rate 0.03 to 0.08), run monthly on the newly lapsed",
        time: "60min",
        tools: "Claude Code + Shopify customer data + your email tool",
        planSeed: "Segment customers past their reorder window | Claude writes winback copy referencing past purchases | test nudge vs small incentive | send monthly batch | report recovered revenue by cohort",
      },
      {
        id: "product-copy-at-scale",
        name: "Product descriptions at scale",
        what: "New SKUs get titles, bullets, descriptions, and SEO fields generated in your brand voice from supplier specs and photos, then pushed to your store. Listing 50 products stops being a lost weekend.",
        mech: "saves_time",
        mathHint: "new_skus_per_month * minutes_per_listing / 60 * owner_hourly_value = monthly time value reclaimed",
        time: "half_day",
        tools: "Claude Code + Shopify + your supplier spec sheets",
        planSeed: "Ingest supplier CSV or spec PDFs | Claude writes copy per your brand voice guide | generate SEO title and meta per SKU | output review sheet | bulk-push approved listings via Shopify API",
      },
      {
        id: "dead-stock-clearance",
        name: "Dead stock flagger and clearance engine",
        what: "Flags inventory that has stopped moving, computes what it costs you to hold, and drafts the clearance campaign to turn it back into cash. Dead stock is money sleeping on a shelf.",
        mech: "makes_money",
        mathHint: "dead_stock_value * recovery_rate = one-time cash recovered per clearance cycle (recovery_rate 0.4 to 0.7 at clearance pricing), plus freed storage cost",
        time: "half_day",
        tools: "Claude Code + Shopify inventory + your email tool",
        planSeed: "Rank SKUs by days-since-last-sale and stock value | Claude proposes markdown tiers per SKU | draft the clearance email and homepage section | schedule the campaign | report cash recovered",
      },
      {
        id: "subscription-cancel-save",
        name: "Subscription cancel-save flow",
        what: "When a subscriber goes to cancel, they get the right save offer for their reason: pause, skip, swap product, or discount, chosen automatically. Saving even a fifth of cancellations compounds into serious LTV.",
        mech: "makes_money",
        mathHint: "cancellations_per_month * save_rate * avg_subscription_value * avg_months_retained = monthly protected revenue (save_rate 0.15 to 0.3 with reason-matched offers)",
        time: "week",
        tools: "Claude Code + your subscription app + Shopify",
        planSeed: "Intercept cancel intent with a one-question reason ask | map reason to save offer rules | Claude personalizes the save message | apply pause or swap via subscription API | track saves and re-cancel rates",
      },
      {
        id: "returns-triage",
        name: "Returns triage and label automation",
        what: "Return requests get checked against your policy, approved or flagged, labeled, and the customer updated, without you in the loop. You only see the weird ones.",
        mech: "saves_time",
        mathHint: "returns_per_week * minutes_per_return / 60 * owner_hourly_value * 4 + (exchange_conversion_rate * returns_per_week * 4 * avg_order_value) = monthly value",
        time: "week",
        tools: "Claude Code + Shopify + your shipping label provider",
        planSeed: "Intake return request via form or email | validate against policy window and condition | offer exchange or credit before refund | generate label via shipping API | update customer and log reason codes for product fixes",
      },
    ],
  },
  {
    key: "saas",
    label: "SaaS and software",
    items: [
      {
        id: "failed-payment-recovery",
        name: "Failed payment recovery",
        what: "Failed charges trigger smart retries plus human-sounding dunning emails that get cards updated, instead of customers silently churning. Involuntary churn is the easiest revenue you will ever recover.",
        mech: "makes_money",
        mathHint: "failed_payments_per_month * recovery_rate * avg_subscription_value * avg_months_retained = monthly protected revenue (good dunning recovers 0.4 to 0.6 of failures)",
        time: "60min",
        tools: "Claude Code + Stripe + your email sender, nothing new to buy",
        planSeed: "Webhook on invoice.payment_failed | schedule retries at smart intervals | Claude writes escalating card-update emails | in-app banner via a flag in your DB | report recovered MRR weekly",
      },
      {
        id: "silent-churn-detector",
        name: "Silent churn detector",
        what: "Watches usage per account and flags the ones that are fading, logins dropping, key features untouched, seats going quiet, weeks before the cancellation email arrives. Cancellations are lagging indicators, usage is the leading one.",
        mech: "makes_money",
        mathHint: "customers_count * monthly_churn_rate * early_flag_share * save_rate * avg_subscription_value * avg_months_retained = monthly protected revenue (save_rate 0.2 to 0.3 with early outreach)",
        time: "week",
        tools: "Claude Code + your existing database + email",
        surprise: true,
        planSeed: "Define health signals from your events table | score accounts weekly against their own baseline | Claude ranks at-risk accounts with the why | draft a personal check-in per account | log interventions and outcomes to tune the model",
      },
      {
        id: "changelog-announcer",
        name: "Changelog-to-announcement writer",
        what: "Every release turns into a customer-facing announcement, an in-app note, and a social post, written from your merged PRs and commit messages. You shipped it, now users actually hear about it, with zero marketing effort.",
        mech: "saves_time",
        mathHint: "releases_per_month * hours_per_announcement * owner_hourly_value = monthly time value, plus announced features lift feature_adoption_rate which feeds retention",
        time: "60min",
        tools: "Claude Code + GitHub + your email tool",
        surprise: true,
        planSeed: "Pull merged PRs since last release tag | Claude translates changes into user-benefit language | generate changelog entry, email, and social post | queue for approval | publish on release",
      },
      {
        id: "behavior-onboarding-emails",
        name: "Trial onboarding emails from actual behavior",
        what: "Instead of a fixed drip, each trial user gets emails based on what they did and did not do: stuck on setup gets help, power users get the upgrade pitch. Onboarding that watches the user converts far better than onboarding that watches the calendar.",
        mech: "makes_money",
        mathHint: "trials_per_month * trial_conversion_lift * avg_subscription_value * avg_months_retained = monthly added revenue (behavior-based onboarding lifts trial conversion 0.2 to 0.4 relative)",
        time: "week",
        tools: "Claude Code + your DB events + your email sender",
        surprise: true,
        planSeed: "Define milestone events for activation | nightly job segments trials by progress | Claude writes the next-best email per segment referencing their actual state | send via your ESP | measure conversion by segment vs old drip",
      },
      {
        id: "trial-expiry-conversion",
        name: "Trial-expiry conversion sequence",
        what: "The last 3 days of every trial get a purpose-built sequence: value recap of what they did, social proof, and a clean ask, then a day-after save offer. Most trials end in silence, which is a choice, not a law.",
        mech: "makes_money",
        mathHint: "expiring_trials_per_month * conversion_lift * avg_subscription_value * avg_months_retained = monthly added revenue (a real expiry sequence adds 0.05 to 0.1 absolute conversion)",
        time: "60min",
        tools: "Claude Code + Stripe + your email sender",
        planSeed: "Query trials expiring in 3 days | Claude writes a personal value recap from their usage | send day -3, -1, and +1 touches | include a one-click extend for engaged non-buyers | track conversion by cohort",
      },
      {
        id: "support-drafts-from-docs",
        name: "Support replies drafted from your docs",
        what: "Every ticket arrives with a suggested answer drawn from your documentation and the customer's account state, so support becomes review-and-send. Halves handle time and keeps answers consistent.",
        mech: "saves_time",
        mathHint: "ticket_count_per_week * minutes_per_ticket * draft_time_saved_share / 60 * team_hourly_value * 4 = monthly time value (draft_time_saved_share around 0.5)",
        time: "half_day",
        tools: "Claude Code + your help desk + your docs, nothing new to buy",
        planSeed: "Ingest new ticket via help desk API | retrieve relevant doc sections and account context | Claude drafts the reply with links | agent approves or edits | auto-resolve the top known-answer categories",
      },
      {
        id: "signup-enrichment-scoring",
        name: "Signup enrichment and lead scoring",
        what: "Every new signup gets enriched from their email domain and public info, scored against your best-customer profile, and routed: high scores get a personal note or a sales ping, everyone else stays in the standard flow. Your sales attention goes where the money is.",
        mech: "makes_money",
        mathHint: "signups_per_month * high_fit_share * touch_conversion_lift * avg_subscription_value * avg_months_retained = monthly added revenue from prioritized touches",
        time: "60min",
        tools: "Claude Code + your DB + Slack",
        planSeed: "Webhook on new signup | look up domain, company size, and tech signals | Claude scores against your ICP rubric | post A-grade signups to Slack with a suggested opener | log score vs eventual revenue",
      },
      {
        id: "metrics-digest",
        name: "Monday metrics digest",
        what: "Every Monday you get one email: MRR, new trials, activation, churn, and the two numbers that moved most, with a plain-english why. No dashboard spelunking, no spreadsheet mornings.",
        mech: "saves_time",
        mathHint: "hours_on_reporting_per_week * owner_hourly_value * 4 = monthly time value, plus faster reaction to a bad week protects churn_rate * mrr",
        time: "60min",
        tools: "Claude Code + Stripe + your DB",
        planSeed: "Pull Stripe and product metrics weekly | compute deltas vs 4-week baseline | Claude writes a 10-line narrative flagging anomalies | email every Monday 7am | link each number to its query for drill-down",
      },
      {
        id: "demo-no-show-recovery",
        name: "Demo no-show recovery",
        what: "Missed demos trigger an instant personal rebook message referencing what the prospect wanted to see, plus a self-serve recording option. Demo no-shows are qualified pipeline evaporating on your calendar.",
        mech: "makes_money",
        mathHint: "demo_no_shows_per_month * rebook_rate * demo_close_rate * avg_subscription_value * avg_months_retained = monthly recovered revenue (rebook_rate around 0.3)",
        time: "60min",
        tools: "Claude Code + your calendar + email or CRM",
        planSeed: "Detect no-show from calendar status | Claude writes rebook note from their signup context | offer live rebook and a 5-min recorded demo | follow up at 1 and 3 days | log recovered demos",
      },
      {
        id: "annual-upgrade-nudges",
        name: "Annual plan upgrade nudges",
        what: "Monthly customers who have stuck around get a personal pitch to switch to annual at the right moment, with the math done for them. Annual plans cut churn and pull cash forward.",
        mech: "makes_money",
        mathHint: "eligible_monthly_customers * upgrade_rate * avg_subscription_value * 12 = cash pulled forward per cycle, plus churn reduction on upgraded accounts (upgrade_rate 0.05 to 0.15 when timed to usage highs)",
        time: "60min",
        tools: "Claude Code + Stripe + your email sender",
        planSeed: "Find monthly subscribers past month 3 with healthy usage | trigger at a usage high point | Claude writes the pitch with their exact savings math | one-click upgrade link via Stripe | track take rate",
      },
      {
        id: "cancel-exit-interview",
        name: "Cancellation exit interview and save flow",
        what: "Cancelling users get a one-question why, and the answer routes to a matched save offer: pause, plan change, or a fix ETA if it is a missing feature. You save some accounts and get honest churn reasons from the rest.",
        mech: "makes_money",
        mathHint: "cancellations_per_month * save_rate * avg_subscription_value * avg_months_retained = monthly protected revenue (save_rate 0.1 to 0.2 with reason-matched offers)",
        time: "half_day",
        tools: "Claude Code + Stripe + your app's cancel flow",
        planSeed: "Insert reason question at cancel intent | map reasons to save offers | Claude personalizes the save message | apply pause or downgrade via Stripe API | tag churn reasons and report monthly",
      },
      {
        id: "feature-request-miner",
        name: "Feature request miner",
        what: "Reads every ticket, cancellation reason, and sales-call note, then keeps a ranked list of what customers actually ask for, weighted by the revenue behind each request. Roadmap arguments end when the money is attached to the ask.",
        mech: "saves_time",
        mathHint: "hours_triaging_feedback_per_week * team_hourly_value * 4 = monthly time value, plus building the top revenue-weighted request protects the churn attributed to it",
        time: "half_day",
        tools: "Claude Code + your help desk + your CRM",
        planSeed: "Ingest tickets, cancel reasons, and call notes weekly | Claude clusters into canonical feature requests | weight each cluster by requesting accounts' MRR | maintain a ranked sheet | monthly summary with movers",
      },
      {
        id: "onboarding-stall-rescue",
        name: "Onboarding stall rescue",
        what: "New paying customers who stall before activating, no data imported, no teammates invited, get spotted and receive the exact unblocking help for their stall point. Customers who never activate are churn that already happened, just not billed yet.",
        mech: "makes_money",
        mathHint: "new_customers_per_month * stall_rate * rescue_rate * avg_subscription_value * avg_months_retained = monthly protected revenue (stall_rate often 0.3+, rescue_rate around 0.3 with targeted help)",
        time: "half_day",
        tools: "Claude Code + your DB events + email",
        planSeed: "Define activation milestones | daily job finds paying accounts stalled past your threshold | Claude picks the matching unblock email or video per stall point | offer a setup call for high-value accounts | track activation rate by cohort",
      },
    ],
  },
];

export const DASHBOARD_ITEM: LibItem = {
  id: "money-dashboard",
  name: "The money dashboard",
  what: "One page where cash is the hero: cash collected and revenue signed for any date range, and every lead source scored by the MONEY it produced, not the lead count. Each source shows leads in, booked, closed, and cash out, sorted by cash, so you see in one glance which channel actually prints money and which one just makes noise. This is the same dashboard the owner of this audit runs their own business on.",
  mech: "both",
  mathHint: "hours_on_manual_reporting_per_week * owner_hourly_value * 4 + (marketing_spend_per_month * wasted_spend_share_found) = monthly value (owners typically find 0.1 to 0.2 of spend going to sources that never produce cash)",
  time: "half_day",
  tools: "Claude Code + the tools where your leads and payments already live, nothing new to buy",
  planSeed: "Tag every new lead with WHERE it came from at the moment it arrives (first touch), and tag every sale with HOW it was booked (last touch) | store leads, customers, and payments in one small database | one page, filterable by date range and source: cash collected, revenue signed, then a table per source with leads, booked, closed, cash, sorted by cash | add efficiency lines: cash per booked call, average deal size | funnel view per channel: leads in, replies, booked, showed, closed, so you see exactly where people leak out",
};
